version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-iwork4se
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5439:5432'
    networks:
      - backend-net

  backend-service:
    container_name: backend-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  postgres_data:
