server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: iwork4se
  profiles:
    active: @spring.profiles.active@
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    web: info
    root: info
