spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
#  datasource:
#    url: jdbc:postgresql://db.fsqxtwerrxfctnvqkxpi.supabase.co:5432/postgres?sslmode=require
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.fsqxtwerrxfctnvqkxpi
    password: 123456
    driver-class-name: org.postgresql.Driver

    hikari:

      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 20000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  redis:
    data:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"
      username: "${REDIS_USERNAME}"
      password: "${REDIS_PASSWORD}"
      database: 0
      ssl: true
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 60s
  sendGrid:
    apiKey: "${SENDGRID_API_KEY}"
    fromEmail: 21096301.khanh@student.iuh.edu.vn
    templateId: d-81068bbbc6324cb08b5543a41810e867
    verificationLink: http://localhost:8080/user/confirm-email
# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: iwork4se-backend-service
    server: http://localhost:${server.port}
    title: Iwork4se backend service
    version: 1.0.0
jwt:
  expiryMinutes: 30
  expiryDays: 7
  accessKey: "RCq2QWKOBB4vrCNdmlqYhfqpUK5SQeVNPOBZqX+awgE="
  refreshKey: "/OzKyt0P8FdZY995196f/QLB7aT2Ts8uSUvixqVjWKs="
  key-prefix: "refresh_token:"
supabase:
  url: https://fsqxtwerrxfctnvqkxpi.supabase.co
  service-role-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcXh0d2VycnhmY3RudnFreHBpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzY4NzE3MiwiZXhwIjoyMDczMjYzMTcyfQ.6kSGWai6pNSdRvO2AnVHbjpuzwA6UYbY-V9lzxa3-YE
  storage:
    bucket: CV
